name: FitnTrain
version: 1.0.0+1
publish_to: none
description: Program for keeping a training diary and a food diary.
environment: 
  sdk: '>=2.19.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  image_picker: ^1.1.2
  charts_painter: ^3.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  calendar_date_picker2: ^2.0.1
  iconify_flutter_plus: ^1.0.4
  iconify_flutter: ^0.0.7
  get_storage: ^2.1.1
  google_fonts: ^8.0.1
  flag: ^7.0.0
  carousel_slider: ^5.1.1
  path_provider: ^2.1.5
  http: ^1.4.0
  csv: ^7.0.0

  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7


  integration_test:
    sdk: flutter
  flutter_test: 
    sdk: flutter

flutter:
  fonts:
    - family: Broken
      fonts:
        - asset: fonts/brokendetroitrusbylyajka.otf
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/backgrounds/
    - assets/default_workouts/
    - assets/nutrition_plan/